Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -35,7 +35,8 @@ jobs:
 
     - name: Run tests with RSpec and Allure
       run: |
-        bundle exec rspec ./spec/features/* --out allure-results
+        bundle exec rspec ./spec/features/* --out allure-results || (echo "RSpec tests failed"; exit 1)
+
 
     - name: Generate Allure report
       run: |
